[package]
name = "advent"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2 = "0.9.9"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"

[[bin]]
name = "day3"
path = "src/day3.rs"
